function [hyperparameters] = DefaultGridsearchHyperparameters()
% DefaultGridsearchHyperparameters
% Setup ALL hyperparameters for GridSearch
% Only for convenience, output (class) parameters can be
% changed manually later (e.g. hyperparameters.isSparse = false)

hyperparameters = ESNHyperparameters(...
    'winScalar', 1,...          % Input Weights | ALSO GRIDSEARCH PARAM
    'winrngDist', 'uniform',...
    'reservoirSize', 1e2,...    % Reservoir | ALSO GRIDSEARCH PARAM
    'spectralRadius', 0.95,...
    'resrngDist', 'uniform',...
    'isSparse', true,...        % Reservoir Sparsity
    'sparsity', 0.05,...       
    'hasBias', true,...         % Bias
    'biasScalar', 1,...
    'fixBiasScalar', true,...           
    'hasFeedback', false,...    % Feedback (cancelled)
    'fbScalar', 1,...
    'fixfbScalar', true,...           
    'leakingRate', 0.5,...      % Leaking Rate | ALSO GRIDSEARCH PARAM
    'activation', 'tanh',...    % Activaiton | help ESNSetup.SetActivation
    'rrCoeff', 1e-8);           % RR solver